# Generated by Django 5.2 on 2025-06-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pedido_fecha_entrega_pedido_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
